# PASOS PARA CONEXION BÁSICA CON BASE DE DATOS #

# 1. ABRIR-CREAR CONEXION
# 2. CREAR PUNTERO
# 3. EJECUTAR QUERY (CONSULTA)
# 4. MANEJAR LOS RESULTADOS DE LA QUERY (INSERTAR | LEER | ACTUALIZAR | BORRAR)
# 5. CERRA PUNTERO
# 6. CERRAR CONEXION
